before_script:
  ## Install ssh-agent if not already installed
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

  ## Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  ## Apply SSH key
  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"

  ## Create SSH directory
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ## Set git credentials
  - git config --global user.email "pvico@uwaterloo.ca"
  - git config --global user.name "Petar Vico"


stages:
  - build-backend
  - deploy-backend


build-backend-job:
  stage: build-backend
  script:
    - echo "Testing backend build job"

deploy-backend-job:
  stage: deploy-backend
  script:
    - echo "Testing backend deployment job"




