workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"


jobs:
  deploy:
    steps:
      - name: Deploy Personal Organizer Backend
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: personal-organizer.petarvico.com
          key: ${{secrets.SSH_KEY}}
          username: root
          
          script : |
            pwd
            ls
            cd personal-organizer
            git checkout main
            git pull
            gradle buildFarJar
            cp personal-organizer-ktor/build/libs/personal-organizer-ktor-all.jar ~/
            cd
            kill -9 `cat backendProcessId.txt`
            nohup java -jar personal-organizer-ktor-all.jar > ktor-backend.log 2>&1 &
            echo $! > backendProcessId.txt

