before_script:
  ## Set git credentials
  - git config --global user.email "pvico@uwaterloo.ca"
  - git config --global user.name "Petar Vico"

  ## ssh into backend server
  - ssh personal-organizer.petarvico.com


stages:
  - build-backend
  - deploy-backend


build-backend-job:
  stage: build-backend
  script:
    - echo "Testing backend build job"

deploy-backend-job:
  stage: deploy-backend
  script:
    - echo "Testing backend deployment job"




