workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"


before_script:
  ## ssh into backend server
  - ssh -tT root@personal-organizer.petarvico.com

  ## get latest from main
  - ls
  - cd personal-organizer
  - git checkout main
  - git pull


stages:
  - build-backend
  - deploy-backend


build-backend-job:
  stage: build-backend
  script:
    - gradle buildFarJar
    - cp personal-organizer-ktor/build/libs/personal-organizer-ktor-all.jar ~/

deploy-backend-job:
  stage: deploy-backend
  script:
    - cd ~/
    - kill -9 `cat backendProcessId.txt`
    - nohup java -jar personal-organizer-ktor-all.jar > ktor-backend.log 2>&1 &
    - echo $! > backendProcessId.txt




